name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: latest


    - name: wasm-pack build
      run: wasm-pack build

    - name: npm install --cwd www
      run: npm install --cwd www

    - name: npm run build --prefix www
      run: npm run build --prefix www


    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Build" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

